### ISSUE TITLE
Add basis setup template which can be overwrite per theme

### ISSUE THREAD

**Issue by jmslbam** [level-level/clarkson-event-manager#4]
Also because block with loops like contacts and downloads are mostly the same?

Also you don't want to forget the https://schema.org/docs/full.html everytime you HTML stuff.

Simple example of Twig files attached as screenshots:

![screen shot 2017-07-12 at 16 07 15](https://user-images.githubusercontent.com/145887/28121709-3c703aca-671c-11e7-9873-538e49709c16.png)
![screen shot 2017-07-12 at 16 06 18](https://user-images.githubusercontent.com/145887/28121715-3f6bdfb8-671c-11e7-8b88-a051d2dc596c.png)

**Comment by NielsdeBlaauw** [comment]
What about an `examples/` folder containing an example implementation. I'm wary of actually loading and displaying a base template because the point was to leave the implementation to the theme. 

This forces people to think about their own implementation instead of trying to build on top of one we prebuilt.
